using System;
using System.Collections.Generic;
using System.Text;
using ISAAR.MSolve.FEM.Integration.Points;


namespace ISAAR.MSolve.FEM.Integration.Quadratures
{
    /// <summary>
    /// Collection of integration points that are generated by a traditional 2D quadrature rule, independent of the 
    /// element type. Thus these points can be cached as static fields of each enum class, so that accessing them is fast 
    /// and storing them is done only once for all elements. All integration points are with respect to a natural 
    /// coordinate system.
    /// Authors: Serafeim Bakalakos
    /// </summary>
    public interface IQuadrature2D
    {
        /// <summary>
        /// The integration points are sorted based on an order strictly defined for each quadrature.
        /// </summary>
        IReadOnlyList<GaussPoint2D> IntegrationPoints { get; }
    }
}
