using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ISAAR.MSolve.XFEM.Integration.Points;

namespace ISAAR.MSolve.XFEM.Integration.Quadratures
{
    /// <summary>
    /// Collections of integration points that are generated by a traditional quadrature rule, independent of the 
    /// element type. Thus these points are cached as static fields of each class, so that accessing them is fast 
    /// and storing them is done only once for all elements. All integration points are with respect to a natural 
    /// coordinate system.
    /// </summary>
    interface IStandardQuadrature2D
    {
        IReadOnlyList<GaussPoint2D> IntegrationPoints { get; }
    }
}
